### ISSUE TITLE
odd loading issue with Spree + Deface, Rails 4.2

### ISSUE THREAD

**Issue by masterkain** [bkeepers/dotenv#177] opened 2015-03-18 07:28 UTC
I'm using `dotenv-rails` 2.0.0 in a Spree 3.0 and Rails 4.2 project.

During app startup/initialization I get this error:

```
/Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `eager_load_paths' for #<Rails::Railtie::Configuration:0x007fe6e4365948> (NoMethodError)
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/railtie.rb:50:in `block (2 levels) in <class:Railtie>'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/railtie.rb:48:in `each'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/railtie.rb:48:in `block in <class:Railtie>'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
```

at first I thought it had something to do with the `deface` gem, but it turns out that this error is raised there just because something else has happened.

I tracked it down to the inclusion of the `dotenv-rails` gem in the project, if I `require: false` it app starts normally.

**Comment by bkeepers** [comment] 2015-03-20 15:32
Interesting. I'm not seeing anything weird on the `dotenv` side. The `deface` gem looks like it does some crazy stuff in the railtie, which makes me suspicious.  Does the error also go away if you do `require: false` on deface?

**Comment by Neschur** [comment] 2015-03-22 12:27
Hello
All variables in array [app.railties.all](https://github.com/spree/deface/blob/master/lib/deface/railtie.rb#L45) is Rails::Engine::Configuration in default Rails+Spree app
After adding this gem to Gemfile - first variable in the array is Rails::Railtie::Configuration

**Comment by Neschur** [comment] 2015-03-22 12:33
this hack
- class Railtie < Rails::Railtie
+class Railtie < Rails::Engine
solves this issues
Maybe this information will be helpful

**Comment by masterkain** [comment] 2015-03-22 14:53
@bkeepers unfortunately I'm in hurry to deliver and downgrading to `1.0.2` makes it work. I'll try to look again at the issue hopefully soon.
@Neschur good find, thanks

**Comment by bkeepers** [comment] 2015-03-23 12:59
Ok. I'm going to close this because I'm fairly confident it's not an issue with dotenv, but let me know if you discover otherwise.

**Closed by bkeepers** 2015-03-23 12:59 UTC

**Comment by phbernard** [comment] 2015-03-23 15:13
Same issue here. Rails works again as soon as I remove the `dotenv-rails` gem or the Spree gems. Apparently these two gems (well, set of gems for Spree) conflict.

Thank you @Neschur for your fix. That's right, changing the `Railtie` declaration in `lib/dotenv/rails.rb` does fix the issue.

**Comment by ryanburnette** [comment] 2015-04-05 22:10
Same issue here. Downgrading to `v1.0.2` got me working again.

I didn't try https://github.com/bkeepers/dotenv/issues/177#issuecomment-84598916.

The issue is closed here, but it would be great if someone with a clear understanding of what causes this problem proposed a change to either dotenv-rails or some other package to mitigate the issue.

**Comment by interhive** [comment] 2015-04-23 17:46
Having same issue with Spree + dotenv. Not sure what the issue is.

**Comment by JohnMorales** [comment] 2015-05-06 10:23
this has been fixed in master of deface. deface was assuming that all configs responded to eager_load_paths. Note that the latest version on rubygems is not the latest version in github, looks like they stopped deploying to rubygems a while back.

**Comment by fzondlo** [comment] 2015-05-12 18:43
+1 @JohnMorales  

Changing my gem file to use `gem 'deface', github: 'spree/deface'` seemed to fix the issue for me.

One thing to mention is that it seemed like it downgraded deface, not upgraded it. I got this output from bundle install:
`Using deface 1.0.0 (was 1.0.1) from git://github.com/spree/deface.git (at master)`

However all the deface dependancies for version 1.0.0 seem to be much newer than the ones with version 1.0.1 so not sure what to think about that.

**Comment by onedanshow** [comment] 2015-05-12 23:59
+1 @JohnMorales and @fzondlo

**Comment by williscool** [comment] 2015-05-30 01:47
for future reference

https://github.com/spree/deface/pull/140

**Comment by yenshirak** [comment] 2015-06-15 12:09
Thanks @fzondlo , `gem 'deface', github: 'spree/deface'` fixed it.

**Comment by mur-wtag** [comment] 2015-09-07 05:28
+1 @fzondlo

**Comment by dimitko** [comment] 2016-06-22 16:49
FYI: I am maintaining a legacy project on Rails 4.0.8 and I cannot use the github version because it says deface 1.0.0 depends on Rails >= 4.1. My local `deface` is locked at `1.0.1`.

Manually specifying `gem 'deface', '1.0.2'` and subsequently doing `bundle update deface` worked however.
